<?php error_reporting(0); ?>


				<label>Total all records</label>
						<label>:</label>
						<label><?php echo $sumAllRisk; 
							$totalrecord = $sumAllRisk;
						?></label>
				<div class="col-md-12">			
				<table class="responsive table-striped table-bordered table-hover" width="100%" border="1" cellspacing="1" cellpadding="1" style="font-size: 12px;"> 
        		<tr>
          			<th><br></th>
          			<th colspan="5"><div align="center"><h3><b>LIKELIHOOD</b></h3></div></th>
        		</tr>
        		<tr>
        			<th width="15%"><h3 align="center"><b> RISK IMPACT</b></h3></th>
        			<td height="20" valign="center"><div align="center"><strong>VERY LOW</strong></div></td>
    				<td valign="center"><div align="center"><strong>LOW</strong></div></td>
    				<td valign="center"><div align="center"><strong>MEDIUM</strong></div></td>
    				<td valign="center"><div align="center"><strong>HIGH</strong></div></td>
    				<td valign="center"><div align="center"><strong>VERY HIGH</strong></div></td>
  				</tr>
          <tr>
            <td valign="center"><div align="right"><strong>CATASTROPHIC</strong></div></td>
            <td bgcolor = "ffff80" align="center"><h4><?php if($allCataVLow == '0'){ ?><?php echo number_format(($allCataVLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allCataVLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allCataVLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allCataVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allCataVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "ffff80" align="center"><h4><?php if($allCataLow == '0'){ ?><?php echo number_format(($allCataLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allCataLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allCataLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allCataLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allCataLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allCataMed == '0'){ ?><?php echo number_format(($allCataMed/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allCataMed/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allCataMed == '0'){ ?> </h4><button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allCataMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allCataMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allCataHigh == '0'){ ?><?php echo number_format(($allCataHigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allCataHigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allCataHigh == '0'){ ?> </h4><button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allCataHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allCataHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allCataVhigh == '0'){ ?><?php echo number_format(($allCataVhigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allCataVhigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allCataVhigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allCataVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allCataVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>
          </tr>
          <tr>
            <td><div align="right"><strong>MAYOR</strong></div></td>
            <td bgcolor = "#90EE90" align="center"><h4><?php if($allMayVLow == '0'){ ?><?php echo number_format(($allMayVLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMayVLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMayVLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMayVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMayVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "ffff80" align="center"><h4><?php if($allMayLow == '0'){ ?><?php echo number_format(($allMayLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMayLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMayLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMayLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMayLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allMayMed == '0'){ ?><?php echo number_format(($allMayMed/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMayMed/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMayMed == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMayMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMayMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allMayHigh == '0'){ ?><?php echo number_format(($allMayHigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMayHigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMayHigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMayHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMayHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allMayVhigh == '0'){ ?><?php echo number_format(($allMayVhigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMayVhigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMayVhigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMayVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMayVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>
          </tr>
          <tr>
            <td><div align="right"><strong>MODERATE</strong><br></div></td>
            <td bgcolor = "#90EE90" align="center"><h4><?php if($allModVLow == '0'){ ?><?php echo number_format(($allModVLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allModVLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allModVLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allModVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allModVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "ffff80" align="center"><h4><?php if($allModLow == '0'){ ?><?php echo number_format(($allModLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allModLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allModLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allModLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allModLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "ffff80" align="center"><h4><?php if($allModMed == '0'){ ?><?php echo number_format(($allModMed/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allModMed/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allModMed == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allModMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allModMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allModHigh == '0'){ ?><?php echo number_format(($allModHigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allModHigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allModHigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allModHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allModHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allModVhigh == '0'){ ?><?php echo number_format(($allModVhigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allModVhigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allModVhigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allModVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allModVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>
          </tr>
          <tr>
            <td><div align="right"><strong>MINOR</strong><br></div></td>
            <td bgcolor = "#90EE90" align="center"><h4><?php if($allMinVLow == '0'){ ?><?php echo number_format(($allMinVLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMinVLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMinVLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMinVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMinVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#90EE90" align="center"><h4><?php if($allMinLow == '0'){ ?><?php echo number_format(($allMinLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMinLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMinLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMinLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMinLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "ffff80" align="center"><h4><?php if($allMinMed == '0'){ ?><?php echo number_format(($allMinMed/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMinMed/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMinMed == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMinMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMinMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "ffff80" align="center"><h4><?php if($allMinHigh == '0'){ ?><?php echo number_format(($allMinHigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMinHigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMinHigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMinHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMinHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allMinVhigh == '0'){ ?><?php echo number_format(($allMinVhigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allMinVhigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allMinVhigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allMinVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allMinVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>
          </tr>
          <tr>
            <td><div align="right" align="center"><strong>INSIGNIFICANT</strong><br></div></td>
            <td bgcolor = "#90EE90" align="center"><h4><?php if($allInsiVLow == '0'){ ?><?php echo number_format(($allInsiVLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allInsiVLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allInsiVLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allInsiVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allInsiVLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#90EE90" align="center"><h4><?php if($allInsiLow == '0'){ ?><?php echo number_format(($allInsiLow/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allInsiLow/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allInsiLow == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allInsiLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allInsiLow"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#90EE90" align="center"><h4><?php if($allInsiMed == '0'){ ?><?php echo number_format(($allInsiMed/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allInsiMed/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allInsiMed == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allInsiMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allInsiMed"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "ffff80" align="center"><h4><?php if($allInsiHigh == '0'){ ?><?php echo number_format(($allInsiHigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allInsiHigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allInsiHigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allInsiHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allInsiHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>

            <td bgcolor = "#FFA07A" align="center"><h4><?php if($allInsiVhigh == '0'){ ?><?php echo number_format(($allInsiVhigh/$totalrecord)*100,2).'%'; ?><?php }else{?> <b><?php echo number_format(($allInsiVhigh/$totalrecord)*100,2).'%'; ?></b><?php }?></h4><?php if($allInsiVhigh == '0'){ ?> <button class="btn-primary" style="display: none;" title="view" type="button" data-toggle="modal" href="#modal-allInsiVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }else{?><button class="btn-primary" title="view" type="button" data-toggle="modal" href="#modal-allInsiVHigh"><span class="glyphicon glyphicon-eye-open"></span></button><?php }?></td>
          </tr>
				</table>
				</div>
				